/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  safelist: [
    "bg-white",
    "bg-gray-400",
    "bg-red-400",
    "bg-orange-400",
    "bg-yellow-400",
    "bg-green-400",
    "bg-sky-400",
    "bg-blue-400",
    "bg-purple-400",
    "bg-pink-400",
    "bg-orange-700",
    "bg-black",
    "bg-gray-700",
    "bg-red-700",
    "bg-orange-500",
    "bg-yellow-600",
    "bg-green-950",
    "bg-sky-900",
    "bg-blue-950",
    "bg-purple-950",
    "bg-pink-900",
    "bg-orange-950",
  ],
};
